### PR TITLE
fix deprecations

### PR DESCRIPTION
**Pull request by braver**

### CODE REVIEW

**Comment by braver** [comment]
@thedaniel I commented out all the specs. They fail because of deprecated methods. The specs that were defined also don't provide any real value as they don't cover anything useful. 

I'm fine with not having specs for now. If I have to weigh the effort of writing them against getting some actual work done (or :sunny: :sunglasses: :beers:), I'd prefer the latter. I'm also not so good at jasmine yet, so that colors my position... but we could always add specs if we want to really rewrite something to guard against regression. On-demand instead of pre-emptive as it were.

How do you feel about this?

**Comment by thedaniel** [comment]
I think the specs were red when i forked the package originally. Just delete them - no need to leave commented-out code around when we can get it out of the git history if we *really* need it.

**Comment by braver** [comment]
Agree wholeheartedly :+1:

**Comment by braver** [comment]
Well, it seems we're ready for 1.0 :tada:

**Pull request merged**
