### PR TITLE
Keyboard Shortcut Updates

### PR DESCRIPTION
**Pull request by hughker**
- The keyboard shortcut of ```shift+enter``` was already being used.
- Changed keyboard shortcut to ```control+shift+enter```

### CODE REVIEW

**Comment by braver** [comment]
Perhaps ctrl-` is a better match? In Sublime this opens the console and it isn't used for anything yet as far as I can tell.

**Comment by thedaniel** [comment]
I don't think it's super crucial what the bindings are set to as long as they don't conflict with stuff in core.

**Comment by braver** [comment]
True. It's also super easy to set your own.

**Comment by braver** [comment]
It's pretty busy at the `shift-enter`, so I'm for changing this and mirroring sublime's console: short and simple. Will merge https://github.com/thedaniel/terminal-panel/commit/9f587a8469b7a2a7c7641a3ebd385a6260980347 later.

screen shot 2015-05-06 at 20 46 14

**Pull request closed without merging**
